# Generated by Django 5.2.8 on 2025-12-02 10:01

import timesheet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('id', models.CharField(default=timesheet.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(max_length=255)),
                ('is_non_productive', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'active_timers',
                'indexes': [models.Index(fields=['employee_id'], name='active_time_employe_58fae2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.CharField(default=timesheet.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(max_length=255)),
                ('is_non_productive', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_records',
                'ordering': ['-end_time'],
                'indexes': [models.Index(fields=['employee_id'], name='time_record_employe_7c82df_idx'), models.Index(fields=['start_time'], name='time_record_start_t_485cb3_idx')],
            },
        ),
    ]
