# Generated by Django 6.0 on 2026-01-15 15:15

import timesheet.models
from django.db import migrations, models
import uuid


def generate_uuid_for_tasks(apps, schema_editor):
    """Generate UUIDs for all existing tasks using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        # Get all tasks that don't have an id yet
        cursor.execute("SELECT name FROM tasks WHERE id IS NULL;")
        tasks = cursor.fetchall()
        
        for (task_name,) in tasks:
            new_uuid = str(uuid.uuid4())
            cursor.execute(
                "UPDATE tasks SET id = %s WHERE name = %s AND id IS NULL;",
                [new_uuid, task_name]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_add_project_description'),
    ]

    operations = [
        # Step 1: Drop primary key constraint from name using raw SQL
        migrations.RunSQL(
            sql="ALTER TABLE tasks DROP CONSTRAINT tasks_pkey;",
            reverse_sql="ALTER TABLE tasks ADD PRIMARY KEY (name);",
        ),
        # Step 2: Alter name field to remove primary_key=True
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
        # Step 3: Add id field as nullable first (without primary_key=True)
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        # Step 4: Populate id field with UUIDs for existing records using raw SQL
        migrations.RunPython(
            code=generate_uuid_for_tasks,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 5: Make id NOT NULL and primary key
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=timesheet.models.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        # Step 6: Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'is_non_productive')},
        ),
    ]
