# Generated by Django 6.0 on 2026-05-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timerecord_ifs_sent_fields'),
        ('timesheet', '0004_task_id_alter_task_name_alter_task_unique_together'),
    ]

    operations = [
    ]
