# Generated by Django 5.2.8 on 2026-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_ifs_reporting_staging_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifsdophead',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='location_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='lot_batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='source_ref1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='source_ref2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifsinventorytransactionhist',
            name='source_ref3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ifsoperationhistory',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsoperationhistory',
            name='reversed_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsprojecttransaction',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsprojecttransaction',
            name='day_confirmed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsreportdata',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsreportdata',
            name='release_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsreportdata',
            name='sequence_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsshopord',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ifsshopord',
            name='release_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ifsshopord',
            name='sequence_no',
            field=models.CharField(max_length=50),
        ),
    ]
