# Generated by Django 5.2.8 on 2026-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_widen_ifs_staging_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifsreportdata',
            name='work_center_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ifsreportdata',
            name='work_center_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
