# Generated by Django 5.2.8 on 2026-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_add_work_center_to_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifsreportdata',
            name='oper_status_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
