# Generated by Django 5.2.8 on 2026-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_add_oper_status_to_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifsoperationhistory',
            name='created_by_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
