# Generated by Django 5.2.8 on 2026-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_add_created_by_employee_id_to_operation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifsoperationhistory',
            name='manufacturing_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ifsoperationhistory',
            name='resource_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
