# Generated by Django 5.2.8 on 2026-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_add_machine_resource_to_operation_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfsEmployeeDirectory',
            fields=[
                ('emp_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ifs_employee_directory',
                'indexes': [models.Index(fields=['company_id'], name='ifs_employe_company_301120_idx'), models.Index(fields=['employee_status'], name='ifs_employe_employe_727fc2_idx')],
            },
        ),
    ]
