# Generated by Django 5.2.8 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_add_ifs_employee_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfsShopOperClocking',
            fields=[
                ('clocking_seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_no', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('clocking_type', models.CharField(blank=True, max_length=50, null=True)),
                ('work_center_no', models.CharField(blank=True, max_length=50, null=True)),
                ('part_description', models.CharField(blank=True, max_length=500, null=True)),
                ('operation_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ifs_shop_oper_clocking',
                'indexes': [models.Index(fields=['transaction_date'], name='ifs_shop_op_transac_cfdbce_idx'), models.Index(fields=['employee_id'], name='ifs_shop_op_employe_48236e_idx'), models.Index(fields=['created_by_employee_id'], name='ifs_shop_op_created_e8b0b9_idx'), models.Index(fields=['order_no'], name='ifs_shop_op_order_n_9f9926_idx')],
            },
        ),
    ]
