# Generated by Django 5.2.8 on 2026-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_add_shop_oper_clocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifsshopoperclocking',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ifsshopoperclocking',
            name='part_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
