# Generated by Django 5.2.8 on 2026-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_add_crew_size_to_shop_oper_clocking'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_column='PART_NO', max_length=200)),
                ('part_description', models.CharField(blank=True, db_column='PART_DESCRIPTION', default='', max_length=500)),
                ('lot_no', models.CharField(blank=True, db_column='LOT_NO', default='', max_length=200)),
                ('wdr', models.CharField(blank=True, db_column='WDR', default='', max_length=50)),
                ('length', models.CharField(blank=True, db_column='LENGTH', default='', max_length=100)),
                ('width', models.CharField(blank=True, db_column='WIDTH', max_length=100, null=True)),
                ('handling_unit', models.CharField(blank=True, db_column='HANDLING_UNIT', default='', max_length=100)),
                ('raw_barcode', models.TextField(blank=True, default='')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'inventory_scan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
