"""Shared helpers/constants for views."""

from copy import deepcopy


NON_PROD_BASE_PAYLOAD = {
    "SourcePage": "TIME_REGISTRATION_JOB",
    "AttInterval": False,
    "AttResult": False,
    "AttAbsence": False,
    "AttLunchBreak": False,
    "AttChangeIntervals": False,
    "AttInOutOrg": False,
    "AttGrossInterval": False,
    "AttManresult": False,
    "AttIndirectClock": False,
    "AttShopClock": False,
    "AttIndirect": False,
    "AttShpord": False,
    "AttWo": False,
    "AttPrjrep": True,
    "CompanyId": "54",
    "WageClass": "WRK",
    "OutTime": None,
    "InPersClass": "Normal",
    "OutPersClass": None,
    "InRegType": "Manually",
    "OutRegType": "Manually",
    "AbsenceWageCode": None,
    "BreakType": "Lunch",
    "WageGrp": None,
    "WageCode": None,
    "ManRsltWageCode": None,
    "ManRsltWageGrp": None,
    "OrgCode": "MNF",
    "Objid1": None,
    "Objid2": None,
    "Objid3": None,
    "Objid4": None,
    "Objid5": None,
    "DayIn1": None,
    "DayIn2": None,
    "DayIn3": None,
    "DayIn4": None,
    "DayIn5": None,
    "DayInType1": None,
    "DayInType2": None,
    "DayInType3": None,
    "DayInType4": None,
    "DayInType5": None,
    "DayOut1": None,
    "DayOut2": None,
    "DayOut3": None,
    "DayOut4": None,
    "DayOut5": None,
    "DayOutType1": None,
    "DayOutType2": None,
    "DayOutType3": None,
    "DayOutType4": None,
    "DayOutType5": None,
    "WageGrpRsltUpd1": None,
    "WageGrpRsltUpd2": None,
    "WageGrpRsltUpd3": None,
    "WageGrpRsltUpd4": None,
    "WageGrpRsltUpd5": None,
    "WageCodeRsltUpd1": None,
    "WageCodeRsltUpd2": None,
    "WageCodeRsltUpd3": None,
    "WageCodeRsltUpd4": None,
    "WageCodeRsltUpd5": None,
    "OrgCodeUpdate1": None,
    "OrgCodeUpdate2": None,
    "OrgCodeUpdate3": None,
    "OrgCodeUpdate4": None,
    "OrgCodeUpdate5": None,
    "ProcStatusUpdate1": None,
    "ProcStatusUpdate2": None,
    "ProcStatusUpdate3": None,
    "ProcStatusUpdate4": None,
    "ProcStatusUpdate5": None,
    "RowProtectionUpdate1": False,
    "RowProtectionUpdate2": False,
    "RowProtectionUpdate3": False,
    "RowProtectionUpdate4": False,
    "RowProtectionUpdate5": False,
    "WageHours": 7.5,
    "RowProtection": False,
    "ResRowProtection": False,
    "ProcStatus": "IncrementsIncluded",
    "ShortName": "TIME-54.MFG.MFG-IND",
    "PurchaseOrderNo": None,
    "PurchaseOrderLine": None,
    "ResourceId": None,
    "PriceAdjustmentId": None,
    "CustomerCompanyId": None,
    "CustomerActShortName": None,
    "CustomerActReportCode": None,
    "Contract": "5402",
    "WorkOrder": None,
    "WorkTask": None,
    "MaintOrg": None,
    "CraftId": None,
    "WoTimeType": None,
    "PlanLineNo": None,
    "IndirectJob": None,
    "Operation": None,
    "TimeType": None,
    "InternalComments": None,
    "InvoiceComments": None,
    "AddShortcut": False,
    "OrderNo": None,
    "ReleaseNo": None,
    "SequenceNo": None,
    "OperationNo": None,
    "TeamId": None,
    "ClockingNoteText": None,
    "WorkCenterNo": None,
    "ResourceShare": None,
    "CrewSize": None,
    "SetupCrewSize": None,
    "TimmanTimeBase": "1",
    "JobTransactionParams": {},
    "ShortcutName": None,
    "FillUpRemainingHours": False,
    "SkipDayOffs": False,
    "MultipleDayReporting": False,
    "IllnessId": None,
}

PROD_BASE_PAYLOAD = {
    **NON_PROD_BASE_PAYLOAD,
}


def get_non_prod_base_payload():
    """Return a safe copy of non-productive IFS payload template."""
    return deepcopy(NON_PROD_BASE_PAYLOAD)


def get_prod_base_payload():
    """Return a safe copy of productive IFS payload template."""
    return deepcopy(PROD_BASE_PAYLOAD)
