"""
Django settings for timesheet_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables - try django_app/.env first, then backend/.env as fallback
env_file = BASE_DIR / '.env'
if not env_file.exists():
    env_file = BASE_DIR.parent / 'backend' / '.env'
load_dotenv(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-91y+up)!iwjj18-xup46&5p7@ykss19ii9gpa2__@t)0yd4fo@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins - required when accessing via HTTPS
# Add your domain(s) here (comma-separated in .env)
csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://mts.astron.biz')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in csrf_origins.split(',') if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timesheet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'timesheet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'timesheet_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support both DATABASE_URL format and separate variables
db_url = os.environ.get('DATABASE_URL', '')
if db_url:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(db_url)
        }
    except ImportError:
        # Fallback if dj_database_url not installed
        pass
        db_url = ''
        
if not db_url:
    # Try separate variables
    db_name = os.environ.get('DB_NAME', 'timesheet_db')
    db_user = os.environ.get('DB_USER', 'postgres')
    db_password = os.environ.get('DB_PASSWORD', '')
    db_host = os.environ.get('DB_HOST', 'localhost')
    db_port = os.environ.get('DB_PORT', '5432')
    
    if db_user and db_password:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': db_host,
                'PORT': db_port,
                'OPTIONS': {
                    'client_encoding': 'UTF8',
                },
            }
        }
    else:
        # Fallback to SQLite for development
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'Europe/Prague')

USE_I18N = True

USE_TZ = True

# Default charset for responses
DEFAULT_CHARSET = 'utf-8'

# Excel timezone - timezone to use when saving timestamps to Excel
# Set to 'system' to use system local time, or a timezone name like 'Europe/Prague'
# Defaults to TIME_ZONE if not set
EXCEL_TIMEZONE = os.environ.get('EXCEL_TIMEZONE', 'system')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration
# https://docs.djangoproject.com/en/5.2/topics/http/sessions/

# Session expires after inactivity (in seconds)
# Default: 2 weeks (1209600 seconds)
# Set to None to expire when browser closes
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', 1209600))  # 2 weeks default

# Whether to expire session when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get(
    'SESSION_EXPIRE_AT_BROWSER_CLOSE', 'False'
).lower() == 'true'

# Session cookie name
SESSION_COOKIE_NAME = 'timesheet_sessionid'

# Whether to save session on every request (extends expiration)
SESSION_SAVE_EVERY_REQUEST = os.environ.get(
    'SESSION_SAVE_EVERY_REQUEST', 'False'
).lower() == 'true'

# Authentication settings
# URL where users are redirected to login (used by @login_required decorator)
LOGIN_URL = '/login/'

# URL where users are redirected after successful login
LOGIN_REDIRECT_URL = '/'